cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED BIGSHARK_PROJECT_ROOT OR NOT DEFINED BIGSHARK_PROTO_TOOLCHAIN_DIR)
  message(FATAL_ERROR
    "BIGSHARK_PROJECT_ROOT and BIGSHARK_PROTO_TOOLCHAIN_DIR are required."
  )
endif()

get_filename_component(
  BIGSHARK_PROJECT_ROOT
  "${BIGSHARK_PROJECT_ROOT}"
  ABSOLUTE
)
get_filename_component(
  BIGSHARK_PROTO_TOOLCHAIN_DIR
  "${BIGSHARK_PROTO_TOOLCHAIN_DIR}"
  ABSOLUTE
  BASE_DIR "${BIGSHARK_PROJECT_ROOT}"
)

find_program(BIGSHARK_LOCKED_NODE_EXECUTABLE NAMES node REQUIRED)
find_program(BIGSHARK_LOCKED_TSC_EXECUTABLE NAMES tsc
  HINTS "${BIGSHARK_PROJECT_ROOT}/node_modules/.bin"
  REQUIRED
)

set(BIGSHARK_PROTOBUF_LOCK_DIR
  "${BIGSHARK_PROJECT_ROOT}/build/.locks"
)
file(MAKE_DIRECTORY "${BIGSHARK_PROTOBUF_LOCK_DIR}")
file(
  LOCK "${BIGSHARK_PROTOBUF_LOCK_DIR}/protobuf-toolchain.lock"
  GUARD PROCESS
  TIMEOUT 600
  RESULT_VARIABLE BIGSHARK_LOCK_RESULT
)
if(NOT BIGSHARK_LOCK_RESULT STREQUAL "0")
  message(FATAL_ERROR
    "Failed to acquire the Protobuf toolchain lock: ${BIGSHARK_LOCK_RESULT}"
  )
endif()

execute_process(
  COMMAND
    "${BIGSHARK_LOCKED_TSC_EXECUTABLE}"
    --project "${BIGSHARK_PROJECT_ROOT}/tools/proto/tsconfig.json"
    --outDir "${BIGSHARK_PROTO_TOOLCHAIN_DIR}"
  WORKING_DIRECTORY "${BIGSHARK_PROJECT_ROOT}"
  COMMAND_ERROR_IS_FATAL ANY
)
execute_process(
  COMMAND
    "${CMAKE_COMMAND}" -E env
    "BIGSHARK_PROJECT_ROOT=${BIGSHARK_PROJECT_ROOT}"
    "${BIGSHARK_LOCKED_NODE_EXECUTABLE}"
    "${BIGSHARK_PROTO_TOOLCHAIN_DIR}/tools/proto/ensure-toolchain.js"
  WORKING_DIRECTORY "${BIGSHARK_PROJECT_ROOT}"
  COMMAND_ERROR_IS_FATAL ANY
)
