cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED BIGSHARK_PROJECT_ROOT OR NOT DEFINED BIGSHARK_NPM_SCRIPT)
  message(FATAL_ERROR
    "BIGSHARK_PROJECT_ROOT and BIGSHARK_NPM_SCRIPT are required."
  )
endif()

find_program(BIGSHARK_LOCKED_NPM_EXECUTABLE NAMES npm REQUIRED)

set(BIGSHARK_TYPESCRIPT_LOCK_DIR
  "${BIGSHARK_PROJECT_ROOT}/build/.locks"
)
file(MAKE_DIRECTORY "${BIGSHARK_TYPESCRIPT_LOCK_DIR}")
file(
  LOCK "${BIGSHARK_TYPESCRIPT_LOCK_DIR}/typescript-generated.lock"
  GUARD PROCESS
  TIMEOUT 600
  RESULT_VARIABLE BIGSHARK_LOCK_RESULT
)
if(NOT BIGSHARK_LOCK_RESULT STREQUAL "0")
  message(FATAL_ERROR
    "Failed to acquire the TypeScript generated-output lock: ${BIGSHARK_LOCK_RESULT}"
  )
endif()

set(BIGSHARK_NPM_ENV)
if(DEFINED BIGSHARK_ENGINE_BINARY)
  list(APPEND BIGSHARK_NPM_ENV
    "BIGSHARK_ENGINE_BINARY=${BIGSHARK_ENGINE_BINARY}"
  )
endif()
if(DEFINED BIGSHARK_CPP_PROTO_VECTOR)
  list(APPEND BIGSHARK_NPM_ENV
    "BIGSHARK_CPP_PROTO_VECTOR=${BIGSHARK_CPP_PROTO_VECTOR}"
  )
endif()

set(BIGSHARK_NPM_COMMAND
  "${BIGSHARK_LOCKED_NPM_EXECUTABLE}" run "${BIGSHARK_NPM_SCRIPT}"
)
if(BIGSHARK_NPM_ENV)
  set(BIGSHARK_NPM_COMMAND
    "${CMAKE_COMMAND}" -E env
    ${BIGSHARK_NPM_ENV}
    ${BIGSHARK_NPM_COMMAND}
  )
endif()

execute_process(
  COMMAND ${BIGSHARK_NPM_COMMAND}
  WORKING_DIRECTORY "${BIGSHARK_PROJECT_ROOT}"
  COMMAND_ERROR_IS_FATAL ANY
)
